<?php

namespace Ens\JobeetBundle\Repository;

/**
 * CategoryAffiliateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryAffiliateRepository extends \Doctrine\ORM\EntityRepository
{
}
