EnsJobeetBundle_homepage:
    path:  /
    defaults: { _controller: EnsJobeetBundle:Job:index }

ens_jobeet:
    resource: "@EnsJobeetBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
