# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.category:
        class: Ens\JobeetBundle\Admin\CategoryAdmin
        arguments: [~, Ens\JobeetBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
            
    admin.job:
        class: Ens\JobeetBundle\Admin\JobAdmin
        arguments: [~, Ens\JobeetBundle\Entity\Job, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Job }
